### ISSUE TITLE
replacement

### ISSUE THREAD

**Issue by keradus** [kelunik/fqn-check#1]
Hi !
Idea behind this package is really great!

This package is not actively maintained, and
some time ago, one of open-source contributor bring this feature into https://github.com/FriendsOfPHP/PHP-CS-Fixer/ as `native_function_invocation` rule.

Maybe you want to deprecate this package and redirect users to PHP CS Fixer to not need to maintain this package ?

**Comment by kelunik** [comment]
The packages doesn't really need any maintenance. It just needs a bug fix to exclude any functions defined in the same namespace. But I added a note to the README anyway. :+1:
