### ISSUE TITLE
Question, or suggestion

### ISSUE THREAD

**Issue by danon** [kelunik/fqn-check#6]
I see you like to check fqn with automatic tool.

Could you also create a tool that verifies that namespaces (e.g. `namespace Foo/Bar`) is in `src/Foo/Bar` folder? And if the namespace doesn't match the file structure, it lists them just like `fqn-check`? What do you think?

**Comment by kelunik** [comment]
I don't have time to work on this and not using this tool personally anymore. Maybe one of the other code style tools in the ecosystem already supports this?
